# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:49
from __future__ import unicode_literals

from django.db import migrations, models
import shops.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[shops.validators.validate_phone_number]),
        ),
    ]
