# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_auto_20171117_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
