# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0005_auto_20171118_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_category',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
