# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import shops.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0006_auto_20171120_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='shop_address',
            field=models.TextField(blank=True, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_category',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Shop Category'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_city',
            field=models.CharField(max_length=128, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_name',
            field=models.CharField(max_length=128, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[shops.validators.validate_phone_number], verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_type',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Shop Type'),
        ),
    ]
