# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-15 14:14
from __future__ import unicode_literals

import customers.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customers', '0002_auto_20171115_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phone_number',
            field=models.CharField(max_length=16, unique=True, validators=[customers.validators.validate_phone_number]),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_sale_quantity',
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
