# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 06:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_auto_20171117_2216'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='user_id',
        ),
    ]
