# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:26
from __future__ import unicode_literals

import customers.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_auto_20171120_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_name',
            field=models.CharField(max_length=128, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_phone_number',
            field=models.CharField(max_length=16, validators=[customers.validators.validate_phone_number], verbose_name='Phone Number'),
        ),
    ]
