# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20171120_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_email_id',
            field=models.EmailField(blank=True, max_length=256, null=True, verbose_name='Email Id'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_sale_price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_sale_quantity',
            field=models.CharField(max_length=16, verbose_name='Sale Quantity'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_sale_quantity_desc',
            field=models.TextField(blank=True, null=True, verbose_name='Sale Description'),
        ),
    ]
