# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-20 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0007_auto_20171120_2212'),
        ('customers', '0010_auto_20171120_2159'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='customer',
            unique_together=set([('shop_id', 'customer_phone_number')]),
        ),
    ]
